### ISSUE TITLE
After update to v1.53e macro execution of "run("Image Sequence...", "open=&fileName");" fails to find directory

### ISSUE THREAD

**Issue by Sethur** [imagej/imagej1#104]
ImageJ:  v1.53e
Windows: Version 10.0.17134.1726
Java: (Zulu 8.46.0.20-SA-win64) (build 1.8.0_252-b14)

After updating ImageJ from v1.53b to v1.53e, my macros that open DICOM image sequences return a "Directory not found" macro error when using:
`run("Image Sequence...", "open=&fileName");`

I first thought there were some problems with special characters in the filenames again, but it turned out that this also happens for very simple directory and file names without spaces like `c:\DirA\Dicom0001.dcm`.

Downgrading ImageJ to 1.53b fixed the problem.

**Comment by Sethur** [comment]
@rasband I encountered the bug using 
`run("Image Sequence...", "open=&fileName");`
in a macro that is called via a batch script, so the variable `fileName` is filled externally. When printed out via `print(fileName);`, the whole path is printed correctly, including the backslashes, so this does not seem to have anything to do with character escaping.

More over, as I already stated, the same macro works fine with ImageJ v1.53b, so the erroneous behavior was only recently introduced with changes made on the way to v1.53b. I have had a look at the recent commits and there were changes at the FileOpener level.

**Comment by rasband** [comment]
What is the full error message? It should include the directory path. What is printed out by "print(fileName);"? Does
`run("Image Sequence...", "open="+fileName);`
work?

**Comment by Sethur** [comment]
`print(fileName)` prints out the full correct path of the first image of the DICOM volume I am trying to open, something like: `c:\SomeFolder\SomeSubFolder\DicomFile_00000.dcm`. The error message is `Directory not found`. I will take a screenshot of the error message tomorrow.

**Comment by rasband** [comment]
This regression is fixed in the ImageJ 1.53f30 daily build. ImageJ was expecting a path to a directory, not to a file.

**Comment by Sethur** [comment]
@rasband: I just finished preparing a minimal working example to replicate the problem, but you were faster, thanks for the quick response.

Also: Thanks for so efficiently taking care of ImageJ1 for all this time. It remains - thanks to people who like you, who invest their so much of their time for free - a lean, efficient and easy-to-extent framework that is still in heavy use by many in the scientific imaging community.
