### ISSUE TITLE
Garbage Collect on Image Close

### ISSUE THREAD

**Issue by redoverture** [imagej/imagej1#106]
After opening large raw image series, memory is not garbage collected until the user clicks the menu bar. This results in high memory usage when opening many sets of images, until the user manually clicks the menu bar before loading another series. It might be more user friendly to automatically run garbage collection after closing an imported raw image.

**Comment by rasband** [comment]
It is normally not a good idea to explicitly call the garbage collector. The Java runtime will do garbage collection when memory needs to be reclaimed and repeated calls to System.gc() can cause performance problems.

**Comment by redoverture** [comment]
It's probably due to the size of the data I'm working with - around 3.6GB raw data for a sequence. If I don't intentionally enable 'Run garbage collector on Status Bar Click' in Memory options, and click it when I notice memory usage is too high, I hit the OutofMemory error dialog (which calls System.gc() anyways...). I wouldn't be surprised if the garbage collection has trouble keeping up with fast paced loading and clearing that much data. Either way, enabling the status bar garbage collector is enough to cover my use case. Just wanted to mention a possible improvement.

Thanks for taking the time to look into it, and for maintaining such a useful project!
