### ISSUE TITLE
Opening DICOM files that use newer VRs (from 2014 and later) such as UC and UR fails

### ISSUE THREAD

**Issue by Sethur** [imagej/imagej1#112]
ImageJ: v1.53i
Java: v1.8.0_262 x64

When opening DICOM files that use newer DICOM VRs such as UC and UR introduced in CP 1031 and CP 1034, the DICOM reader will throw an error message stating "Unable to decode DICOM header".

I have debugged the issue with the ImageJ1A repository  (which is still on v1.53h) and the issue lies in some of the newer VRs having an official tag length of 4 bytes (as opposed to 2 bytes for other VRs), which is not yet reflected in the DicomDecoder class. This will lead to the elementLength being read from the wrong bytes, sometimes resulting in a very large element length skipping the rest of the DICOM header and finally resulting in an unexpected EOF.

The problem can be fixed by adding the relevant VRs after line 261 in DICOM.java:

```
	private static final int AE=0x4145, AS=0x4153, AT=0x4154, CS=0x4353, DA=0x4441, DS=0x4453, DT=0x4454,  
		FD=0x4644, FL=0x464C, IS=0x4953, LO=0x4C4F, LT=0x4C54, PN=0x504E, SH=0x5348, SL=0x534C,   
		SS=0x5353, ST=0x5354, TM=0x544D, UI=0x5549, UL=0x554C, US=0x5553, UT=0x5554,  
		OB=0x4F42, OW=0x4F57, SQ=0x5351, UN=0x554E, QQ=0x3F3F,   
		OF=0x4F46, OL=0x4F4C, OD=0x4F44, UC=0x5543, UR=0x5552;  
```

and also adding them to the switch-case-structure after line 463:
```
		switch (vr) {
			case OB: case OW: case SQ: case UN: case UT: 
			case OD: case OF: case OL: case UC: case UR:
```

The new VRs added above can be found [here](http://dicom.nema.org/medical/Dicom/2017c/output/chtml/part05/chapter_7.html#sect_7.1.2) in Table 7.1-1.

I could create a pull request for these changes if necessary.

Edit: I created a pull request for this fix: #113

**Comment by Sethur** [comment]
Should I have posted this on the ImageJ1A tracker?

**Comment by rasband** [comment]
Please provide at least one example DICOM that I can use to validate this fix.

**Comment by Sethur** [comment]
Update: It seems that it will still be necessary to teach all new VRs to the DicomDecoder class, since ImageJ1 currently cannot properly differentiate between implicit and explicit VRs and will just try to match the respective 2 bytes to a known list of VRs and assumes "explicit" if there is a match. Thus, the default for unknown VRs cannot be a tag length of 4 bytes, since the default right now is to assume that it was a data element with an implicit VR. The risk of this failing is increasing with each new VR, but to mitigate this, the decoder must have some other way of distinguishing between implicit and explicit data elements, which would require a more complete implementation of the DICOM standard.

For now I will just add all new tags that were introduced in the past few years with their correct tag lengths, which should - at least until further VRs are introduced - fix the issue.

**Comment by Sethur** [comment]
I created a new pull request #116  that adds all new VRs until the current standard (2021a). You can test it with the example DICOM [file](https://github.com/AlizaMedicalImaging/MDCM/releases/download/v1.0.27/VR-2019.dcm) above, which should now load without decoding errors.

As I mentioned in the pull request, it would probably be a good idea to implement the handling between implicit and explicit VRs properly to avoid future errors with new and unknown VRs.

**Comment by Sethur** [comment]
@rasband Did the tests with VR-2019.dcm work for you?

**Comment by rasband** [comment]
The ImageJ 1.53j12 daily build, which has the fixes to support newer VRs, opens the VR-2019.dcm file.
