### ISSUE TITLE
Grid lines not removed after rotate with preview and enlarge image

### ISSUE THREAD

**Issue by nelas** [imagej/imagej1#117]
Hello,

When I rotate images interactively using using the enlarge image option and preview mode, the grid lines are not removed after rotation.

1. Run `Image > Transform > Rotate... `
2. Change `Grid lines` to 10, and activate `Enlarge image` and `Preview`
3. Click OK > Grid is still visible

Without activating `Enlarge image` the grid is removed automatically.

Cheers,
Bruno

**Comment by rasband** [comment]
This bug is fixed in the ImageJ 1.53j17 daily build.
