### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by elcodedocle** [imagej/imagej1#119]
Is this code published under Apache/MIT/BSD license? If not, which are the licensing conditions and where are they described? I've searched the website and repo for these conditions but have not found any document describing them. 

Some publisher at https://sourceforge.net/projects/imagej/ mentions it's public domain code under `GNU Library or Lesser General Public License version 2.0 (LGPLv2)` _and_ `GNU General Public License version 2.0 (GPLv2)`, which makes it a little confusing as those 2 licenses have significantly different conditions. And the publisher is not linked back anywhere from the official site as this repo is, so I have no way to confirm that license claim is even legitimate...

To clarify this, would it be possible to add such document as a LICENSE file to this git repository root, following Github convention?

**Comment by dprodanov** [comment]
Vanilla ImageJ (e.g. ij.jar) is public domain and not GPL or something like
that.
The person who can clarify is Wayne Raspband (cc).

best regards,

Dimiter Prodanov

**Comment by imagejan** [comment]
Maybe this helps clarifying the situation for the different components:
https://imagej.net/Licensing

**Comment by elcodedocle** [comment]
> Maybe this helps clarifying the situation for the different components:
> https://imagej.net/Licensing

This is what I was looking for. Thank you! :-)
