### ISSUE TITLE
image => stacks => orthogonal views : unexpected binning along Z when binning stack along X

### ISSUE THREAD

**Issue by robach** [imagej/imagej1#121]
I applied binning 
x 2
y 1
z 1
to a stack of 41 images 1040x1040.
Binning works fine on the stack, 
but when calculating the orthogonal views an unexpected x2 binning is present along z.
(YZ cut is only 21x1040, XZ cut is only 520x21)
Thanks.

**Comment by rasband** [comment]
I cannot reproduce this problem using the following macro.

```
  run("Make Sphere");
  run("Scale...", "width=1024 height=1024 depth=41 average process create");
  run("Bin...", "x=2 y=1 z=1 bin=Average");
  run("Orthogonal Views");
```

![Screenshot](https://user-images.githubusercontent.com/1633637/122650821-ec540080-d102-11eb-9680-f31d2963d8a2.png)
