### ISSUE TITLE
Imagestack.getVoxel()

### ISSUE THREAD

**Issue by erexhepa** [imagej/imagej1#13]
Hi, 

I was working with the class ImageStack.java and by chance I was getting some strage values (0) for some indexes. I realised that my indexes were going beyond the limits of the stack in the X,Y direction and the values returned where all 0. I was wondering if this was a design choice or a bug ? Shouldn't an error be through? Something like this java.lang.IndexOutOfBoundsException? 

Elton

**Comment by rasband** [comment]
The getVoxel() method in the latest ImageJ daily build (1.51a7) throws an IndexOutOfBoundsException if x, y or z are beyong the stack limits.

**Comment by erexhepa** [comment]
Hi,

Great then. I will grab the latest build then. The one I have is not very old (1.50b) but there seems to be a few fixes transitioning to the latest.

Thanks,

Elton
