### ISSUE TITLE
Macro editor should allow opening file types it can edit

### ISSUE THREAD

**Issue by dnebdal** [imagej/imagej1#130]
I'm using Fiji / ImageJ 1.53c on Windows.

Plugins / Macros / Edit... opens a file dialog, set to show "files of all types (\*.\*)".  If I try to open a python .py file, I get the error _File name must end with ".java", ".txt" or ".js"_  - but I can open a dummy text file, and then use File / Open... inside the macro editor to open the same python file, which seems inconsistent?

**Comment by rasband** [comment]
This bug is fixed in the ImageJ 1.53m23 daily build.

**Comment by dnebdal** [comment]
Excellent, thanks. And apologies for opening the bug against the wrong version.
