### ISSUE TITLE
ImageJ 1.53f51 - click and hold behaves like control click

### ISSUE THREAD

**Issue by hyungsongnam** [imagej/imagej1#132]
Hello,
I already posted to imagej/imagej2, but I realize that might not be the appropriate forum.
The latest update delivered ImageJ 1.53f1. While browsing through some images, I noticed that scrolling through images opened the right click menu on the image window.
This was because, now, click and hold on an image window brings up the options menu as control click does (same as right click).
Is this a programmed in new behavior of ImageJ or is this a bug?
I downloaded two previous versions of Fiji, and those didn't have the same behavior.
I also checked the latest ImageJ daily version, and it also behaved the same (i.e., click and hold --> right click or control click menu).
A screen capture is attached.
What I'm doing in the screen capture is first click and drag to scroll through the image, then click and hold.
With the latest Fiji update, I get the right click menu, but with two previous version of Fiji I don't.
For now, I downgraded to ImageJ 1.52.
Thank you.
Sincerely,
Hyung-song Nam, PhD

https://user-images.githubusercontent.com/36607862/133952682-c038958e-0207-4a33-894e-82e3514aad71.mov

https://user-images.githubusercontent.com/36607862/133952693-27aa4c95-7262-45e6-a2db-2f312fbf7d7a.mov

https://user-images.githubusercontent.com/36607862/133952699-2760b170-de1f-4f0c-84c4-e96fac7f3e4b.mov

**Comment by rasband** [comment]
This bug is fixed in the ImageJ 1.53m30 daily build or work around it by not selecting the "hand" tool and scrolling by dragging while holding down the space bar.
