### ISSUE TITLE
Creating a new Image(); instance hides exceptions

### ISSUE THREAD

**Issue by odinsbane** [imagej/imagej1#141]
I'm using IJ 1.53o29 in the following example no exceptions will be shown. It works as expected with IJ 1.53a

```java
import ij.*;

public class HiddenExceptions{
    public static void main(String[] args){
        new ImageJ();
        System.out.println(args[1]);
    }

}
```

**Comment by rasband** [comment]
This ImageJ 1.53m regression is fixed in the latest daily build (1.53o31). The commit is at
https://github.com/imagej/imagej1/commit/9a15154d045cb57f3bc2366adc1e1b06e4e5eaef,
