### ISSUE TITLE
`ImageProcessor.isBinary` always returns `false`

### ISSUE THREAD

**Issue by rimadoma** [imagej/imagej1#17]
The documentation of the method states _"Returns 'true' if this is a binary image (8-bit-image with only 0 and 255)"_ whereas the whole body of the method is just:
```java
public boolean isBinary() {
	return false;
}
```

**Comment by axtimwalde** [comment]
Sure, that is the default implementation in the base class.  But `ByteProcessor` overrides it:

https://github.com/imagej/imagej1/blob/master/ij/process/ByteProcessor.java#L1233

according to the spec.  It's may be confusing that `ShortProcessor` does not override it, but would [0.255] make any sense there?

**Comment by rimadoma** [comment]
Ah yes, I forgot that `ImageProcessor` is an abstract super class. Maybe it'd be clearer to leave the method abstract in `ImageProcessor`?
