### ISSUE TITLE
Show status when creating new stack

### ISSUE THREAD

**Issue by mcib3d** [imagej/imagej1#20]
Hi Wayne,

Is it possible to remove, or better use a verbose option, the ShowStatus call in NewImage.CreateStack ? I use it a lot, and in a loop, in my 3D suite, and I would prefer not to show so many text ;) . Thanks a lot.

Thomas

**Comment by rasband** [comment]
In the latest ImageJ daily build (1.51g1), the message is only displayed with stacks 250 MB or larger.

**Comment by mcib3d** [comment]
Hi,
That´s perfect. Thanks.

Thomas
