### ISSUE TITLE
Roundtrip to/from TIFF alters ROI slice positions

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej1#21]
Here is an example macro illustrating the problem:
```javascript
run("Mitosis (26MB, 5D stack)");
makeRectangle(39, 43, 29, 29);
roiManager("Add");
Stack.setPosition(2, 1, 1); // jump to channel 2
makeRectangle(77, 86, 50, 49);
roiManager("Add");
run("Select None");
run("From ROI Manager");
home = call("java.lang.System.getProperty", "user.home");
path = home + "/mitosis-with-overlay.tif";
print("Saving TIFF with overlay to: " + path);
saveAs("Tiff", path);
run("Close All");
open(path);
run("To ROI Manager");
roiManager("Show None");
roiManager("Select", 1);
```

The expected behavior is that the 2nd channel should be active, not the 2nd Z position.

**Comment by rasband** [comment]
This bug is fixed in the latest ImageJ daily build (1.51g4). The run("From ROI Manager") macro function was not transferring the ROI positions to the overlay if the "Associate 'Show All' ROIs with slices" option in the ROI Manager was not enabled in More>>Options.
