### ISSUE TITLE
ImageStatistics getStatistics API

### ISSUE THREAD

**Issue by bgyori** [imagej/imagej1#26]
This change: https://github.com/imagej/imagej1/commit/3740ec9f44e8ada30cda7a41d15083b3626fa0d9#diff-6f1421fe86889bb3a171a110c60adf57R839
breaks the API of ImageStatistics. Namely, getStatistics() without arguments now doesn't calculate some of the statistics (e.g. xCenterOfMass) that it previously did. These values are left undefined. I have a longstanding plugin that assumed getStatistics() would run with ALL_STATS and it was broken in a rather hard-to-debug way because of this change. I'm guessing others might be affected.

**Comment by bgyori** [comment]
Also, the ImageProcessor.getStatistics() doesn't take arguments and calls ImageStatistics.getStatistics without an option argument - it's therefore not possible to calculate all statistics using the ImageProcessor's getStatistics anymore.

**Comment by rasband** [comment]
This regression is fixed in the latest ImageJ daily build. ImageProcessor.getStatistics() now calculates ALL_STATS and there is a new getStats() method, which is up to 70 times faster, that only calculates histogram, area, mean, min and max, standard deviation and mode.
