### ISSUE TITLE
[Point tool -> Label points] has no effect

### ISSUE THREAD

**Issue by mirekslouf** [imagej/imagej1#27]
I double click on the [Point tool], which opens the [Point tool] window. If I check or uncheck [Label points] option, it has no effect - the small labels are always drawn on the image.

The same is true for lines, rectangles and other objects...

I work with ImageJ 1.51h on Win7 64-bit.

**Comment by rasband** [comment]
I was not able to duplicate this problem with either the point tool or the multi-point tool.

Line and area selections do not have labels unless they are added to an overlay and "Show labels" is enabled in the Image>Overlay>Labels dialog. The easiest way to label line and area selections is to enable "Add to overlay" in the Analyze>Set Measurements dialog and then press "m" (Analyze>Measure) after creating a selection, which will add the selection to an overlay and turn on the "Show labels" option.

**Comment by mirekslouf** [comment]
Thank you for the explanation. Now I realized where the problems was (and is):

0) Close ImageJ (if running) and open new instance of ImageJ.
1) Create a new blank image: File - New - Image...
2) Open dialog: Image - Overlay - Labels... (uncheck all checkboxes; in my installation, they ARE unchecked by default).
3) Select [Point tool] measure arbitrary distance, press [Ctrl+M] =>labels ARE there.
4) Reopen dialog Image - Overlay - Labels... and uncheck all checkboxes AGAIN => labels disappear.

Conclusion: In my installation of ImageJ, if I start manual measurements (Ctrl+M), the Labels are set on AUTOMATICALLY, regardless of the fact that I have unchecked them before.

I tend to think that this is a bug, but perhaps it is intentional behavior of the program?

**Comment by rasband** [comment]
There are two kinds of labels. There are overlay selection labels, normally white, which are enabled ad disabled in the Image>Overlay>Labels dialog and there are point labels in point selections, which are enabled and disabled in the "Point Tool" dialog. The latest ImageJ daily build (1.51i12) fixes a bug that caused point labels of point selections in an overlay to not reflect the status of the "Label points" checkbox in the "Point Tool" dialog.
