### ISSUE TITLE
Zooming causes a crash

### ISSUE THREAD

**Issue by e-sev** [imagej/imagej1#33]
Hey there,
just noticed that the zooming function with "+" in the newest ImageJ version causes a crash after clicking "+" ~ 4 times.
OS is Mac OS X, 10.11.6, Java 8, Update 131 (seems to be the newest version) and ImageJ version 1.50i.
The image is a small 12x12 px image.

Maybe anyone of you can fix this bug.

Greetings,
Severin

**Comment by ctrueden** [comment]
This bug is fixed in ImageJ 1.51n, released yesterday.
