### ISSUE TITLE
bug in Binner?!

### ISSUE THREAD

**Issue by tischi** [imagej/imagej1#37]
Hi All,
I think at below place the clone() method fails to produce an actual copy of the Calibration object:
https://github.com/imagej/imagej1/blob/master/ij/plugin/Binner.java#L68
Thus, in the following lines of code not only the calibration of the imp2 (the output image) but also, falsely, of the imp (the input image is changed).

**Comment by imagejan** [comment]
You're right. This groovy script reproduces the issue when run on a calibrated image:

```groovy
// @ImagePlus imp

import ij.plugin.Binner

println imp.getCalibration()

binner = new Binner()
binned = binner.shrink(imp, 3, 3, 3, Binner.MAX)

println imp.getCalibration()
println binned.getCalibration()
```

**Comment by rasband** [comment]
The Binner class in the latest ImageJ daily build (1.51o23) fixes this bug by using createImagePlus() instead of clone().
