### ISSUE TITLE
Spline fitting an ANGLE Roi

### ISSUE THREAD

**Issue by awalter17** [imagej/imagej1#39]
Hello!

I noticed that when you try to spline fit an ANGLE Roi, it results in a closed Roi (see below images). Is this intended behavior? @rasband please let me know your thoughts on this.

**ANGLE Roi**
![angle-roi](https://user-images.githubusercontent.com/8901182/28135972-c0338c04-670d-11e7-9fff-415ba7fb430c.png)

**Spline Fit ANGLE Roi**
![spline-fit-angle-roi](https://user-images.githubusercontent.com/8901182/28135981-c793b76c-670d-11e7-9a7b-7dfef05027c2.png)

Thank you very much, 

Alison

**Comment by imagejan** [comment]
Good catch.
Interestingly, the command `Edit > Selection > Fit Spline` complains that it requires a polygon or polyline selection when run on an angle ROI, so this really only concerns the *Spline fit* option of the Line Width dialog, which (I think) should not even apply to angle selections at all.

**Comment by awalter17** [comment]
> Interestingly, the command Edit > Selection > Fit Spline complains that it requires a polygon or polyline selection

@imagejan Thanks for checking that command! I completely forgot about it. 

When you try to run `Edit > Selection > Fit Spline` on a Freehand Roi or a Freehand line Roi, it works without complaint (though it does change the type of your Freehand Roi to a Polygon and your Freeline Roi to a Polyline). However, when you try to click the _Spline fit_ option in the Line Width dialog for these Rois you can't.

This raises the question: should you be able to spline fit Freehand, Freeline, and Angle Rois?

**Comment by rasband** [comment]
> I noticed that when you try to spline fit an ANGLE Roi, it results in a closed Roi (see below images). Is this intended behavior? @rasband please let me know your thoughts on this.

This bug is fixed in the latest ImageJ daily build (1.51q16).
