### ISSUE TITLE
Commands in the right-click popup menu do not get recorded

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej1#41]
The macro recorder doesn't record commands launched from the popup menu (e.g. *right-click > Rename...* or *right-click > Duplicate...*), while the same commands *do* get recorded as expected when run from the main menu (*Image > Rename...* or *Image > Duplicate...*).

**Comment by rasband** [comment]
This bug is fixed in the latest ImageJ daily build (1.51q29).
