### ISSUE TITLE
May it be that ROI type is encoded by one byte (6) and not two (6-7)?

### ISSUE THREAD

**Issue by yfp** [imagej/imagej1#42]
If it's [true](https://github.com/imagej/imagej1/blob/f129e9bd95be4808d2a669b08c6427e7a61bba04/ij/io/RoiEncoder.java#L154-L156), it's better to correct [the doc comment](https://github.com/imagej/imagej1/blob/f129e9bd95be4808d2a669b08c6427e7a61bba04/ij/io/RoiDecoder.java#L16).

**Comment by rasband** [comment]
It is true so I updated the comment in RoiDecoder.java.
