### ISSUE TITLE
Macro language's return statement issue 

### ISSUE THREAD

**Issue by Mathieu-Prouveur** [imagej/imagej1#45]
Hello everyone,

I wonder if this is a well known fact and accepted behavior from ImageJ macro language that the return statement works fine with parenthesis for numbers but not for strings :

```java
function fooString(){
	return ("test") ;
}
function fooNumber(){
	return (1) ;
}
print("result String",fooString() ,"result Number", fooNumber());
```
This outputs `result String 0 result Number 1`, whereas  :

```java
function fooString(){
	return "test" ;
}
function fooNumber(){
	return 1 ;
}
print("result String",fooString() ,"result Number", fooNumber());
``` 
outputs `result String test result Number 1`

Even more puzzling to me is that
```java
function fooString(){
	return ("123") ;
}
s=fooString();
print(s,(s+2));
```
this actually ouputs `123 125` so if the string represents a number it actually ouputs the number represented and not the string representing it.

It is not a big deal as long as the user knows it, but I wonder if there is a simple way to fix this by either making the `return( var );` syntax throw an exception or ideally make this syntax work.

**Comment by rasband** [comment]
I do not know of a simple way to make this syntax work so the latest daily build (1.51r8) aborts the macro when it is used with the error message "String enclosed in parens".

**Comment by Mathieu-Prouveur** [comment]
Okay thanks!

Yes I noticed the `return` statement actually works perfectly fine, the problem is in the evaluation of the syntax `(var)`, as shows the code below :

```python
s="1";
print(s+1,(s)+1);
```
It outputs `11 2` ,

 so the problem is not restricted to the `return` statement but as you say to the  "String enclosed in parens"syntax which for some reason converts string to num.

**Comment by Mathieu-Prouveur** [comment]
Actually I just found out it is not just restricted to strings as shows this code :
```
L=newArray(10);
print((L)+1);
```
This outputs `1` instead of crashing like `print(L)` would, here (L) is interpreted as a number instead of an array
