### ISSUE TITLE
All keyboard shortcuts are duplicated on latest Fiji update - OSX

### ISSUE THREAD

**Issue by etarena** [imagej/imagej1#50]
Running ImageJ 2.0.0-rc-62/1.51s / Java 1.8.0_66 (64-bit) on a OS X Yosemite 10.10.5... 
Duplicate measurements are made only the first time ‘command+M’ is used… afterwards, single measurements are calculated.  Also - this does not appear to occur with the ‘M’ shortcut alone - then it is also single measurements.  This issue was originally posted on the ImageJ Forum [here](http://forum.imagej.net/t/command-m-measurement/8450).

**Comment by etarena** [comment]
This issue appears to extend to all keyboard shortcuts ... all are duplicated.  This was [posted recently](http://forum.imagej.net/t/all-keyboard-shorcuts-are-duplicated-on-latest-fiji-update-osx/8479) on the ImageJ Forum as well.

**Comment by ctrueden** [comment]
Fixed by imagej/imagej-legacy@bab66b8de7fcf21993ce18bc384631dbd7879e30.
