### ISSUE TITLE
AVI reading issue (indx/ix00 files)

### ISSUE THREAD

**Issue by zzyzyman** [imagej/imagej1#56]
There seems to be an issue with the AVI Reader.  When opening a valid AVI file, AVI Reader states: "An error occurred reading the AVI file. Required item 'ix00' not found."  And yet these files open fine with other software I have.

This collection of 2.5gb AVI files from a variety of sources are each typically comprised of 450 frames @ 30fps that internally use an 'indx' composed of 2 entries: a 410 frame 'ix00' and a 40 frame 'ix00'.  The plugin will only read the first block of 410 frames based on the 'dwTotalFrames' value in the 'avih' header.

In the Java source for AVIReader, there's a comment "number of frames in ix00; ignored: not always trustworthy" in the 'readAVI2Index' function that is responsible for reading these 'dwDuration' values of 410 and 40.

Smaller files and larger files (eg. 4.7gb @ 900 frames) that don't use the 'indx'/'ix00' indexing schema work fine.

**Comment by rasband** [comment]
Please make available an AVI file that exhibits this problem.

**Comment by zzyzyman** [comment]
Attached is a 27248w x 64h uncompressed AVI file of alternating colours that exhibits the issue.  Its odd size is for a local sports arena with this size of a LED display board.  The file will unzip to approximately 2.5gb in size.

Files of this nature come from a variety of sources and the majority of them seem to exhibit this behaviour with ImageJ.

Thanks for all the hard work!

[Rotating Image.avi.zip](https://github.com/imagej/imagej1/files/1969603/Rotating.Image.avi.zip)

**Comment by zzyzyman** [comment]
I believe I've found the error... endian ordering is the issue.

AVIReader.java has FOURCC_ix00 = 0x30307869 when it should be FOURCC_ix00 = 0x78693030.  Internally, java was attempting to compare 'ix00' off disk with the '00ix' constant and it was failing.

On another note, to be consistent with '00db'- and '00dc'-suffixed declarations, FOURCC_ix00 should technically be declared as FOURCC_00ix. Doing so would be consistent with the internal AVI occurrences of '00db' & '00dc'.

**Comment by rasband** [comment]
The latest ImageJ daily build (1.52b25), which has the proposed AVI_Reader fix, successfully opens the Rotating Image.avi file.
