### ISSUE TITLE
Odd-width AVI files don't load

### ISSUE THREAD

**Issue by zzyzyman** [imagej/imagej1#57]
When I attempt to load the attached 1703x64 (24-bit) AVI file, I receive an error.
    **An error occurred reading the AVI file.
    Data chunk size 326976 too short (327168 required).**

1703W * 64H * 3 bytes/pixel = 326976 bytes
1704W * 64H * 3 bytes/pixel = 327168 bytes

And yet the file loads fine with other video players.

Does this mean that any and all odd-width AVI files won't load within ImageJ?

[Flashing AVI_1703x64_30s.avi.zip](https://github.com/imagej/imagej1/files/1982215/Flashing.AVI_1703x64_30s.avi.zip)

**Comment by rasband** [comment]
This bug is fixed in the latest ImageJ daily build (1.52c1).
