### ISSUE TITLE
Bug in RoiManager

### ISSUE THREAD

**Issue by tischi** [imagej/imagej1#61]
@rasband 

I think I found two issues here:

https://github.com/imagej/imagej1/blob/master/ij/plugin/frame/RoiManager.java#L434

1. The code does not check whether `n>=0`, but always adds the `n`

2. The index `n` is added to the end of the name and not to the beginning as it says in the JavaDoc. 
I would prefer that it actually is added to the beginning

**Comment by rasband** [comment]
These bugs are fixed in the latest ImageJ daily build (1.52f1). View the changes at
https://github.com/imagej/imagej1/commit/3117bcd7bcd4ac008341cf5044116da2eba48b9c
