### ISSUE TITLE
IJMath class missing in repo

### ISSUE THREAD

**Issue by Bio7** [imagej/imagej1#62]
Hello Wayne,

I just updated my application to the latest commit and didn't find the referenced ij.util.IJMath class used in the CurveFitter.

**Comment by rasband** [comment]
The ij.util.IJMath class is in the 1.52f6 commit:
https://github.com/imagej/imagej1/commit/97693cc266a4038e1945db0dae2d735b752f6583

**Comment by Bio7** [comment]
Great, thanks!
