### ISSUE TITLE
ImageProcessor.setLineWidth() method not overriding Fiji preferences

### ISSUE THREAD

**Issue by lollopus** [imagej/imagej1#63]
I am not able to override programmatically the value stored in the _Fiji Edit/Options/Line width menu_. Specifically, my task involves javascript to permanently draw the outline of a ROI in an image. To replicate:

```
importClass(Packages.ij.gui.NewImage);
importClass(Packages.ij.gui.Roi);
importClass(Packages.java.awt.Color);

var image = NewImage.createRGBImage(“Untitled”, 500, 500, 1, NewImage.FILL_BLACK);
var roi = new Roi(100, 100, 300, 300);
image.getProcessor().setColor(new Color(255, 0, 0));
image.getProcessor().setLineWidth(50);
image.getProcessor().draw(roi);
image.killRoi();
image.show();
```

The problem is that while the red color is correctly applied, the line width of 50 is not. The actual line width used is that stored manually in the Fiji menu. See also forum discussion http://forum.imagej.net/t/imageprocessor-setlinewidth-method-not-overriding-fiji-preferences/12169/2

**Comment by rasband** [comment]
You can avoid this problem by not calling ImagePlus.getProcessor(), which sets the line line width to the global line width. Here is an example:

```
  ip = new ColorProcessor(500,500);
  ip.setColor(Color.red);
  ip.setLineWidth(50);
  roi = new Roi(100,100,300,300);
  ip.draw(roi);
  new ImagePlus("Untitled",ip).show();

```
