### ISSUE TITLE
Cannot save pasted image content in javascript

### ISSUE THREAD

**Issue by lollopus** [imagej/imagej1#64]
After copy/pasting programmatically the content within a rectangular ROI from one location to another of the same image and saving, the saved file does not include this modification! Saving the image manually instead does embed the copied pixels. The issue can be replicated with the following:

```
importClass(Packages.ij.IJ);
importClass(Packages.ij.ImagePlus);
importClass(Packages.ij.gui.NewImage);
importClass(Packages.ij.gui.Roi);
 
var image = NewImage.createRGBImage(“Untitled”, 1000, 500, 1, NewImage.FILL_RAMP);
var rectRoi = new Roi(parseFloat(500), parseFloat(0), parseFloat(500), parseFloat(250)); image.setRoi(rectRoi);
image.copy(false);
rectRoi.setLocation(parseFloat(0), parseFloat(0));
image.paste();
image.show();
IJ.saveAsTiff(image, “[your favourite directory path here]/temp.tif”);
```

I’ve tried different variants of the same methods without success. See also forum discussion http://forum.imagej.net/t/help-with-saving-pasted-image-content-in-javascript/12146

**Comment by rasband** [comment]
This bug is fixed in the latest ImageJ daily build (1.52f7). View the code changes at
https://github.com/imagej/imagej1/commit/bc9fa25681a8664d24b9a298cbd10f70e477e60f
