### ISSUE TITLE
BatchConverter on Mac

### ISSUE THREAD

**Issue by petebankhead** [imagej/imagej1#65]
Hi, I'm having some trouble with _Process &rarr; Batch &rarr; Convert..._ running on a Mac.

Specially, if I press a button to set the input or output directory, and choose a valid directory, the plugin immediately runs - with no opportunity to change the other directory, or to run it again after I have made further changes.

I believe it's because of [this code](https://github.com/imagej/imagej1/blob/2a6c191b027b5b1f5f22484506159f80adda21c5/ij/plugin/BatchConverter.java#L152) inside `actionPerformed`:
```java
if (IJ.isMacOSX())
   {gd.setVisible(false); gd.setVisible(true);}
```

This then results in the `showDialog()` method above proceeding too early beyond `gd.showDialog();`.

**Comment by rasband** [comment]
This bug is fixed in the latest ImageJ daily build (1.52f12). View the code changes at
https://github.com/imagej/imagej1/commit/6dc407f55257869576c65533f075bc73a9cbf35d
