### ISSUE TITLE
Programmatically generated overlay of PointRois not shown when file saved and reopened if stack has > 1 slice

### ISSUE THREAD

**Issue by lollopus** [imagej/imagej1#68]
To reproduce this odd behaviour:
1. run the javascript below (adapted from @rasband in https://github.com/imagej/imagej1/issues/67#issuecomment-428630079)
2. notice the PointRois
3. save and close file
4. reopen file
**5. notice that the PointRois are not shown**; they are however still present in the overlay as shown by Overlay>List elements

6. now repeat the above but reduce the stack size from 2 to just 1 slice (i.e. set d = 1)
**7. notice that the PointRois are now visible!**

8. repeat steps 1-2 and then manually add a few points with the multi-point tool
9. save and close file
10. reopen file
**11. notice that the programmatically generated points are not shown, while those added manually are shown!**

```
importClass(java.util.Random);
importClass(Packages.java.awt.Color);
importClass(Packages.ij.IJ);
importClass(Packages.ij.gui.Overlay);
importClass(Packages.ij.gui.PointRoi);
 
var	w = 500, h = 500, d = 2,
img = IJ.createImage("Demo","8-bit black",w,h,d),
overlay = new Overlay();
 
 img.setOverlay(overlay);
 img.show(); 
 ran = new Random();

 for (var i = 1; i <= d; i++) {
   var roi = new PointRoi();
   for (var j = 0; j < 5; j++) {
     x = ran.nextFloat()*w;
     y = ran.nextFloat()*h;
     roi.addPoint(x,y);
  }
  roi.setPosition(i);
  roi.setStrokeColor(new Color(200, 255, 100));
  roi.setPointType(3);
  roi.setSize(4);
  roi.setShowLabels(false);
  overlay.add(roi);
} 
```

**Comment by rasband** [comment]
This bug is fixed in the latest ImageJ daily build (1.52h32). View the code changes at https://github.com/imagej/imagej1/commit/2206fef95e71316ba698eead97146b3b51efd3c9.
