### ISSUE TITLE
Support ImageJ>Preferences and Quit on macOS with Java 9+

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej1#71]
For standalone ImageJ1, _ImageJ > Preferences_ doesn't show up at all but otherwise things are fine. In case of Fiji, however, this blows up as an error message on startup. 

`com.apple.eawt.ApplicationListener` has been deprecated. Hence, its uses in https://github.com/imagej/ImageJA/blob/master/src/main/java/MacAdapter.java have to be replaced. For more instructions on migration see https://stackoverflow.com/questions/9239287/what-is-the-alternative-for-deprecated-com-apple-eawt-applicationlistener.

**Comment by petebankhead** [comment]
The presence of MacAdapter at the top level (not in any package) is also troublesome when using ij.jar in a modular application in JDK 9+, with errors:
```
java.lang.module.InvalidModuleDescriptorException: MacAdapter.class found in top-level directory (unnamed package not allowed in module)
```
Removing MacAdapter and everything builds without complaint.

**Comment by rasband** [comment]
The ImageJ 1.53d59 daily build has the MacAdapter class in the ij.plugin package.
