### ISSUE TITLE
MaximumFinder().getMaxima finds maxima in blank images

### ISSUE THREAD

**Issue by LauLauThom** [imagej/imagej1#74]
See this [forum post ](https://forum.image.sc/t/maximumfinder-finds-maxima-in-black-images/24015)

In empty images (all pixels to 0 or 1) it still finds 4 maxima, all of coordinates (0,0) !
```python
from ij.plugin.filter	import MaximumFinder
from ij import IJ

# Create a blank image
imp = IJ.createImage("Untitled", "8-bit white", 20, 20, 1) # white or black, -> find 4 peaks at 0,0 !?
#imp = IJ.createImage("Untitled", "8-bit noise", 20, 20, 1) # -> this is fine

# Detect maxima
tolerance = 10
excludeOnEdge = False
Polygon = MaximumFinder().getMaxima(imp.getProcessor(), tolerance, excludeOnEdge)

# Print x,y of maxima
for x,y in zip(Polygon.xpoints, Polygon.ypoints):
	print x,y
```

**Comment by rasband** [comment]
I cannot reproduce this bug. The following JavaScript outputs "polygon.npoints: 0" when I run it on the current version of ImageJ (1.52m).

```
  imp = IJ.createImage("Untitled", "8-bit white", 20, 20, 1);
  tolerance = 10;
  excludeOnEdge = false;
  polygon = new MaximumFinder().getMaxima(imp.getProcessor(), tolerance, excludeOnEdge);
  print("polygon.npoints: "+polygon.npoints);
```

**Comment by imagejan** [comment]
@LauLauThom the "problem" is that the public fields `xpoints` and `ypoints` of an empty `java.awt.Polygon` get initialized as `int[4]` (likely for performance reasons), as illustrated by this Groovy script:

```groovy
import java.awt.Polygon

p = new Polygon()

println p.xpoints // [0, 0, 0, 0]
println p.ypoints // [0, 0, 0, 0]
```

So indeed you'll first have to use `npoints` to check how many points you can query.

**Comment by LauLauThom** [comment]
Wow, thanks for the tips, not obvious indeed !
