### ISSUE TITLE
ImageJ/FIJI Linux Image Window will not maximize until 'zoom' is applied

### ISSUE THREAD

**Issue by TomkoLA** [imagej/imagej1#75]
I was recommended by Jan Eglinger to post to @rasband what appears to be a bug I discovered while using FIJI (1.52i), but is also present in ImageJ (1.52a) on the Linux version. The original issue report with more details may be found here: https://github.com/fiji/fiji/issues/220 . Since it has been pointed out that it is 'normal behavior' for ImageJ to be unable to fully maximize a newly opened image window using the Linux version, I tried to use the zoom feature (Image>Zoom>In, Out; I used the + and - hotkeys) and suddenly the image window was able to be maximized fully; as normal and expected. This ability to fully maximize any image window has been typical behavior on all of the Windows versions of ImageJ I have used, so it does appear to be a legitimate bug with the Linux version of ImageJ. The first image depicts the image window stuck at 50% size and cannot be maximized. The second image is after I have either hit the 'zoom in' or 'zoom out' hotkey and then tried maximizing the window.
![ImageJ_wont_maximize](https://user-images.githubusercontent.com/24944130/54829878-63309380-4c85-11e9-93de-a964999aebb8.png)
![ImageJ_after_plusminus_maximized](https://user-images.githubusercontent.com/24944130/54829887-662b8400-4c85-11e9-94ec-32a4c35946a6.png)

**Comment by imagejan** [comment]
To be precise, I didn't say it's a bug, but that this is intended behavior.

**Comment by TomkoLA** [comment]
For what it's worth, the issue seems to have stemmed from the XFCE window manager that came with my Linux distribution. I switched to the Compiz window manager for different reasons and there is no longer a problem maximizing the image windows in ImageJ or FIJI. Maybe this info will be useful to someone else with this problem in the future.
