### ISSUE TITLE
All slices (except current slice) deleted following "Undo" following pencil/paintbrush/floodfill tool

### ISSUE THREAD

**Issue by agclark12** [imagej/imagej1#79]
Here's a strange one. If I open a stack and then draw something using the pencil, paintbrush or flood fill tool and then "Undo", I lose all of the slices from the stack except for the current slice. The window resets to default zoom settings, and the slice slider at the bottom disappears. If I check the image properties, sure enough, there is only one slice. This occurs whether the stack is a time- or z-series. This does not occur if I select a region, Draw and then Undo. Working on fiji-2.0.0-pre-8 on OSX 10.14.4 (Mojave). Thanks!

**Comment by rasband** [comment]
This bug is fixed in the ImageJ 1.52p14 daily build.
