### ISSUE TITLE
ImageStack getVoxel when out of bounds

### ISSUE THREAD

**Issue by H-Y-S** [imagej/imagej1#81]
The documentation (docstring in the code) specifies that ImageStack:getVoxel should return NaN when the coordinates are out of bounds. Looking at the source code it seems that it instead throws an IndexOutOfBounds exception. The behaviour is ok, but the docstring should be updated to reflect the actual behaviour.

**Comment by rasband** [comment]
I updated the Javadoc documentation for the ImageStack.getVoxel() method.
