### ISSUE TITLE
StackStatistics always returns zero as median

### ISSUE THREAD

**Issue by walkernoreen** [imagej/imagej1#82]
The StackStatistics class (https://github.com/imagej/imagej1/blob/master/ij/process/StackStatistics.java)
seems to always return zero for the image median.

To reproduce the issue (jython script):
```
from ij import IJ
from ij.process import StackStatistics

IJ.run("MRI Stack (528K)");
imp=IJ.getImage()

IJ.run(imp,"Add...", "value=20 stack"); # just to make sure all values are >0 in our test image

stats = StackStatistics(imp) 
print "mean: ", stats.mean
print "min: ", stats.min
print "max: ", stats.max
print "median: ", stats.median # 0.0 ...should be >0
```

results into this output:
```
mean:  55.9346908999
min:  20.0
max:  255.0
median:  0.0
```

**Comment by rasband** [comment]
This bug is fixed in the latest ImageJ daily build (1.52q6). Source code changes are at
https://github.com/imagej/imagej1/commit/3efe48fa0947dabc33b1a9e97e960e04e33a4c61
