### ISSUE TITLE
Is imagej2 released / on github as well?

### ISSUE THREAD

**Issue by nicostubi** [imagej/imagej1#84]
Hello,

I am completely new to imagej. I have a few questions:

- on their website, I saw that there is a v2 (imagej2). I installed the bundle fiji, that is bundling a version 1.52. Version that seems to match with this repository, right?
- is there a version 2 of imagej on github?
- I saw that imagej2 has been released - but only in rc2 - in 2017. So I assume the development branch of imagj is still based on v 1.52, right?

Best Regards,
Nicolas

**Comment by imagejan** [comment]
For questions like these, the [image.sc forum](https://forum.image.sc) is the best place actually.
Please have a look at https://imagej.net/ImageJ#Flavors

If you install Fiji, you'll have ImageJ2 and a legacy layer with the latest 1.x version.

The source code is in many components, all in the `imagej` and `scijava` orgs here on GitHub.

**Comment by nicostubi** [comment]
thanks.

**Comment by ctrueden** [comment]
Just to answer this question succinctly here as well: [ImageJ 1.x](https://github.com/imagej/imagej1) and [ImageJ2](https://github.com/imagej/imagej) are separate codebases. ImageJ2 is modular, with one (optional) piece being a legacy layer enabling backwards compatibility with ImageJ 1.x. See also [this presentation](https://imagej.github.io/presentations/2017-02-16-imagej2-neubias/#/20) for further details.
