### ISSUE TITLE
Bad scrollbar handle visibility on Windows 10 using ImageJ 1.52r (and previous versions)

### ISSUE THREAD

**Issue by Sethur** [imagej/imagej1#85]
OS: Windows Version 10.0.17134.1069
Java: Build 1.8.0_221, x64
ImageJ: Version 1.52r

I recently switched from Windows 7 to Windows 10 on a machine where I am using ImageJ frequently and I noticed that the click-and-drag-handle on the  scrollbars is very hard to see when using Windows 10 as opposed to Windows 7, as demonstrated in the screenshot below. For some reason, the rendering of the scrollbars seems to have changed when working with Windows 10's modern UI. I tried using ImageJ2 with Fiji as well and the problem was persisting.

Does anyone have an idea where to fix this in the source, then I could commit a pull request to ImageJ1A.

![image](https://user-images.githubusercontent.com/2142589/68460705-ca955680-0208-11ea-960d-23c12529462c.png)

**Comment by rasband** [comment]
This bug is fixed in the latest ImageJ daily build (1.52s19). Code changes are at
https://github.com/imagej/imagej1/commit/6de3c13344d70c42999e57281a6f8eb962394e06

![Screenshot](https://user-images.githubusercontent.com/1633637/68498543-181fbc80-0225-11ea-8cf4-27b53b08b064.png)

**Comment by Sethur** [comment]
@rasband Thank you for the quick response. The suggested solution is almost perfect, but:

1) The size of the scroll bar handle is now too small (less than half the width) compared to the previous solution, i.e. it's hard to actually hit it with the mouse. See screenshot number 1 or your example above.
2) The background color of the scrollbar ist somewhat ugly when compared with the default Windows 10 (or lower) solution. An ideal solution would be colors as in this Github edit window or in the Windows explorer (i.e. scroll bar handle in dark grey, background in suitable light grey). See screenshot number 2.

Should I reopen this issue?

![image](https://user-images.githubusercontent.com/2142589/68606824-9099ae00-04af-11ea-8283-fb3f78374559.png)

![image](https://user-images.githubusercontent.com/2142589/68606912-c0e14c80-04af-11ea-8e43-c6948e7b691b.png)

**Comment by Sethur** [comment]
Update: Apparently, the width of the scrollbar handle and the overall appearance of the scrollbar is dependent on the java version in use: I see the small scrollbar handle and the bumpy arrow buttons with OpenJDK 8u232b09 x64 from AdoptOpenJDK (as in the screenshot above) but the wide handle and the flat buttons with the Oracle Java Build 1.8.0_221. Strange.

**Comment by imagejan** [comment]
This looks to me like an issue with different look-and-feel settings in Java. Some plugins (3D Viewer and/or 3D Manager IIRC) caused a change of look-and-feel in Java windows in the past. @Sethur do you have any other plugins active, or have used them before taking the above screenshots? If so, can you test with a freshly started ImageJ?

**Comment by Sethur** [comment]
I tried with a fresh install and the problem, at least with Oracle JVMs, went away. Maybe it had something to do with the fact that this was originally an ImageJ2 (no Fiji) install.

No, however, there is a new issue when using OpenJDK 8 (from AdobtOpenJDK), but I'll post a separate issue about that.

As a conclusion, I would still advise to change the scollbars to a more default look, i.e. make the handle darker and use the light grey background from before, but I'm fine either way. My scrollbar (with the Oracle JVM) now looks like below.

![image](https://user-images.githubusercontent.com/2142589/68661284-0139dc80-053b-11ea-9f07-a25f0df64951.png)

**Comment by rasband** [comment]
I could not find a way to make the handle smaller. The Scrollbar.setForeground(Color) method does not do anything. The latest ImageJ daily build (1.52s38) makes the background a little darker, so scrollbars on Windows appear more standard. The screenshot below shows what scrollbars now look like on Windows.

![Screenshot](https://user-images.githubusercontent.com/1633637/68821956-a51ba900-065d-11ea-8510-ebe8f4d4fb91.png)

**Comment by Sethur** [comment]
@rasband: When comparing the ImageJ scrollbar handle and scrollbar background colors to those of the Windows 10 explorer (and other standard Win32 API windows), it can be seen that - in both environments - there are actually 5 shades of grey involved. Those are, in increasing order of blackness:

1. The (background) color of the scrollbar and arrow buttons (grey-white)
2. The color of the scrollbar handle when not used (i.e. clicked on) or hovered over (light grey)
3. The color of the scrollbar handle when hovering over the scrollbar, but not the handle itself (medium grey)
4. The color of the scrollbar handle when directly hovering over but not dragging it (dark grey)
5. The color of the scrollbar handle when actively dragging it (grey-black).

The problem with ImageJ in Windows 10 was, that the color (1) and the color (2) where practically identical.

The best fix for the stack sliders would be to change the color (1) (inactive handle) to a lighter shade of grey, i.e. the same one as used for the arrow buttons.

Your first suggested fix changed the color (1) to white, which worked fine for default ImageJ windows, but it leaves the scrollbars somewhat non-standard and would make them partly disappear on white surfaces.

Your second and latest proposed fix from 1.52s38 is also not optimal, because...
- ... scrollbars have nearly identical colors (1) and colors (4), which makes the handle disappear into the scrollbar when directly hovering over it (see second screenshot).
- ... the inverted colors of background and handle are also not the expected behavior

Lastly, the fixes were only implemented for stack image windows, not for sliders appearing at different places, like in the brightness adjustment dialog, etc. (see screenshot 3).

My suggested solution would be to change the background scrollbar color (1) **everywhere** to the combination rgb(240,240,240) = 0xf0f0f0, which is the same as on the arrow buttons.

**Comparing Windows 10 Explorer horizontal scrollbar background color with ImageJ background color from 1.52r (before the fix attempts)**
![image](https://user-images.githubusercontent.com/2142589/68857961-4e0ce700-06e4-11ea-8436-39caeee61509.png)



**Hovering problem with latest fix (1.52s38). Imagine a mouse pointer on the handle**
![image](https://user-images.githubusercontent.com/2142589/68856746-8eb73100-06e1-11ea-8220-e2d868dbf0ee.png)

**Disappearing scrollbars in other windows with latest fix (1.52s38)**
![image](https://user-images.githubusercontent.com/2142589/68856724-865ef600-06e1-11ea-9fbe-83a5557aea3e.png)

**Comment by Sethur** [comment]
@rasband

PS: When looking at the brightness slider window in the last screenshot, I think I understand why the darker scrollbar background color was introduced at some point. It was probably because with the default color, the scrollbar background would be identical to the window color for these kinds of windows.
Fixing this properly would actually require a different scrollbar color scheme for windows with white background and windows with light grey background. If you can set the scrollbar background colors independently (it seems that why, because your latest fix did not affect other windows), I would suggest using the inverted colors look from fix 1.52s38 for those kinds of windows and the normal look with background color 0xf0f0f0 for everything with white background.

**Comment by rasband** [comment]
In today's daily build (1.52s45), the backgrounds of all Windows scrollbars are set to near white (R=G=B=245). I will remove this work around when the OpenJDK developers fix this bug.

**Comment by Sethur** [comment]
@rasband Thanks for the quick action, now everything looks good. BTW, the color issue is not an OpenJDK bug, it also happens with the older Oracle JVMs. I guess it's just an issue with the default flat look of scrollbars in Windows 10. With previous Windows versions and their elevated buttons and handles, visibility of the handle was never an issue.
