### ISSUE TITLE
When adding a calibration bar, the "Bold Text" setting is not retained

### ISSUE THREAD

**Issue by Sethur** [imagej/imagej1#88]
OS: Windows 10
Java: OpenJDK v1.8u232 x64
ImageJ: v1.52r

When adding a calibration bar via `Analyse->Tools->Calibration Bar`, all changed dropdown choices, numbers and checkboxes will be remembered, but not the `Bold text` setting, i.e. when the dialog is opened again, every setting is left at its last value (how it should be) but one has to check `Bold Text` again if so desired.

Update: Added a pull request that should fix the issue: #89

**Comment by rasband** [comment]
This bug fix is in the latest ImageJ daily build (1.52s48).
