### ISSUE TITLE
ImagePlus.getShortTitle() behaviour is problematic with file names containing mutliple spaces and dots

### ISSUE THREAD

**Issue by SarenT** [imagej/imagej1#94]
Hi,

I guess the purpose of a getShortTitle() isn't to get any short title but an identifying yet shorter version of the title.
However, the implementation seems to be problematic in certain scenarios. e.g.
File name/title "2020.01.24 - Image 1.tif" would return "2020.01". If multiple images such as "2020.01.24 - Image 2.tif", "2020.01.24 - Image 3.tif" are present, the short title isn't identifying at all.
This behaviour affects plugins such as TrackMate.

I think, instead of getting last index of spaces, spaces need to be replaced with empty string. Subsequent last index of a dot would then remove the file extension. Then the function would return this: "2020.01.24-Image1".

An alternative could be to trim spaces left and right and then remove file extension:
"2020.01.24 - Image 1"
Either way is better and more useful than current implementation. I can submit a merge request if maintainers agree with it.

**Comment by rasband** [comment]
The getShortTitle() method in the latest ImageJ daily build (1.52t45) returns "2020.01.24-Image1" for a title of "2020.01.24 - Image 1.tif".

This is what the code looks like:
```
   /** If the image title is a file name, returns the name
      without the extension and with spaces removed,
      otherwise returns the title shortened to the first space.
   */ 
   public String getShortTitle() {
      String title = getTitle().trim();
      int index = title.lastIndexOf('.');
      boolean fileName = index>0;
      if (fileName) {
         title = title.substring(0, index);
         title = title.replaceAll(" ","");
      } else {
         index = title.indexOf(' ');
         if (index>-1 && !fileName)
            title = title.substring(0, index);
      }
      return title;
    }
```
