### ISSUE TITLE
Bug calculating calibrated length of a line

### ISSUE THREAD

**Issue by ndefrancesco** [imagej/imagej1#98]
Hi @rasband !
I just found that in the latest builds the reported line length in a calibrated image changes wierdly with orientation. 

I traced the bug to this line, which was rewriten as part of a6ce76d08829152e5b679166ebb4d685a43a263c , but has a pair of parenthesis missing:

https://github.com/imagej/imagej1/blob/a6ce76d08829152e5b679166ebb4d685a43a263c/ij/gui/Line.java#L425

This should read:
``` java
		return Math.sqrt(sqr((x2d-x1d)*cal.pixelWidth) + sqr((y2d-y1d)*cal.pixelHeight));
```

Cheers!

**Comment by rasband** [comment]
This regression is fixed in the ImageJ 1.52v1 daily build and also in version 1.52u available via the Help>Update ImageJ command.
